export { ReactComponent as Logo } from './logo.svg'
export { ReactComponent as DashBoard } from './dashboard.svg'
export { ReactComponent as AdManage } from './adManage.svg'
export { ReactComponent as GuideIcon } from './guide.svg'
export { ReactComponent as Alarm } from './alarm.svg'
export { ReactComponent as Setting } from './setting.svg'
export { ReactComponent as Profile } from './profile.svg'
